// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY_09eI3CUZs8cr7r6dfY7wY9poStmPHo',
    appId: '1:916202713258:android:75e3f978e9eebbe288a0d3',
    messagingSenderId: '916202713258',
    projectId: 'turnetes-62746',
    databaseURL: 'https://turnetes-62746-default-rtdb.firebaseio.com',
    storageBucket: 'turnetes-62746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYuXGs0idggLbRSXiIOpAhjw12Ph8xdTw',
    appId: '1:916202713258:ios:35d4b452d5553b3488a0d3',
    messagingSenderId: '916202713258',
    projectId: 'turnetes-62746',
    databaseURL: 'https://turnetes-62746-default-rtdb.firebaseio.com',
    storageBucket: 'turnetes-62746.appspot.com',
    iosClientId: '916202713258-vs69sm4cpagurdgrabva4cp6n00c1m5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.turnetes',
  );
}
